### ISSUE TITLE
The app no longer works, needs to support API v16.

### ISSUE THREAD

**Issue by andreaspijay** [n3d1117/appdb#91] opened 2023-08-03 06:44 UTC
The app reports: "This API version is o longer supported. Please upgrade your software: https://telegra.ph/API-v15-to-v16-migration-guide-05-17"

Any plans to update the app?

**Comment by n3d1117** [comment] 2023-08-03 07:25
Duplicate of #87

**Closed by n3d1117** 2023-08-03 07:25 UTC
