### ISSUE TITLE
New api

### ISSUE THREAD

**Issue by Freddelloyd** [n3d1117/appdb#88] opened 2023-07-10 09:18 UTC
Please update the app to support the new api

**Comment by Freddelloyd** [comment] 2023-07-15 20:32
@stev3fvcks @n3d1117 Please it would make everyone very happy

**Comment by Isntreallyme23** [comment] 2023-07-16 22:16
Please Please update the app to support the new api 👍

**Comment by n3d1117** [comment] 2023-07-16 22:52
Closing as duplicate of #87. @stev3fvcks (who now maintains this app) is aware of the API changes and will work on an update asap

**Closed by n3d1117** 2023-07-16 22:52 UTC

**Comment by Freddelloyd** [comment] 2023-07-18 09:45
Thank you bro
