### ISSUE TITLE
Search Bar Font Black on Grey in Dark Theme

### ISSUE THREAD

**Issue by dtimekeeper** [n3d1117/appdb#34] opened 2019-06-05 08:56 UTC
Search bar font remains black on grey when the Dark theme is used on V1.0.

(Amazing work on the app, super slick and the library/download along with the rest of the API integration is super well done).
![C828FCEA-5083-4E87-BC45-29EA27266124](https://user-images.githubusercontent.com/5618459/58943658-0b0e1700-8735-11e9-94ef-8e1364736daf.jpeg)

**Comment by n3d1117** [comment] 2019-06-05 09:13
Can't seem to reproduce it. What device and iOS version are you on? Is the text still gray when you close and reopen the app?

**Comment by dtimekeeper** [comment] 2019-06-05 09:27
Hi - I’m on an iPad Pro 11” running, uh, iOS13 Developer beta 1. Running the app theme in Light, Dark, and Darker, and on the iOS light and dark themes produce the same black on grey result.

I’m happy to test further if needed.

**Comment by n3d1117** [comment] 2019-06-05 11:05
Hmm so the text is always gray regardless of the theme (Light, Dark, Darker, iOS Light, iOS Dark) you use? Does it affect all the in-app search bars? Please check News and See All too.

It could be a specific bug in [SwiftTheme library](https://github.com/wxxsw/SwiftTheme) related to search bars in iOS 13. Sadly I don't have any iOS 13 devices to test this myself.

**Comment by dtimekeeper** [comment] 2019-06-05 16:33
Yep, it's always grey regardless of what theme I use, and it's across all
the search bars, both in the Search tab and the 'See all' popup. It
probably is an ios13 specific bug in the theming library.

Thanks for checking into it and for creating the app.

**Comment by n3d1117** [comment] 2019-06-07 13:14
@dtimekeeper  I found the issue! It was my fault. Will be fixed in the next update!

**Comment by greybaron** [comment] 2019-07-18 23:25
@n3d1117 on an iPad Pro 11", iOS 13 dev beta 4, appdb 1.0.1 (latest release) the search text is still black in the appdb dark mode. Only the "Search iOS Apps" text is light grey.

**Comment by n3d1117** [comment] 2019-07-20 12:17
Hello @greybaron, thanks for reporting. This might be fixed in 847a823 (don't have an iOS 13 device so I can't test). Could you try to install [this test build](https://github.com/n3d1117/appdb/files/3413577/appdb_847a823.ipa.zip) and see if it's fixed? Thanks
I'll reopen the issue for now.

**Comment by greybaron** [comment] 2019-07-31 15:56
Sorry for the late reply. The issue is still present in the test build, tested on dev beta 5. "Search iOS Apps" looks good but the search text is black

**Comment by n3d1117** [comment] 2019-07-31 20:26
Ok @greybaron, thanks for reporting, seems like things changed a bit with iOS 13. Since I can't afford to update to a macOS beta, you'll have to wait until Xcode 11 and iOS 13 are publicly released for this to be fixed. I'll keep this issue open until then.

**Comment by n3d1117** [comment] 2019-10-02 16:57
Hi @greybaron @dtimekeeper, please test [release 1.0.2](https://github.com/n3d1117/appdb/releases/tag/v1.0.2)! I was not able to reproduce this issue using latest version. Let me know! I will keep this open for now

**Comment by dtimekeeper** [comment] 2019-10-04 00:32
@n3d1117 confirmed fixed for me on iOS 13.2 dev beta 2 and release 1.0.2. :)

**Closed** 2019-10-04 12:13 UTC
